version: '3'
services:
  db:
    image: mariadb:11.4-ubi
    container_name: sms-gateway_db
    restart: always
    command: --wait_timeout=28800 --interactive_timeout=28800
    volumes:
      - /opt/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=UP5yeFxRcvtMBzjdfNmT6p
      - MYSQL_USER=sms-gateway
      - MYSQL_PASSWORD=Bpj7hXNCextgnzSWckFybV
      - MYSQL_DATABASE=smsd
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 5
  backend:
    image: fizcko/sms-gateway:latest
    container_name: sms-gateway_server
    restart: always
    ports:
      - 5000:5000
    devices:
      - "/dev/ttyUSB2:/dev/phone"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=sms-gateway
      - MYSQL_PASSWORD=Bpj7hXNCextgnzSWckFybV
      - MYSQL_DATABASE=smsd
      - GAMMU_DEVICE=/dev/phone

